"""
MLflow tracking utilities.

This module records information about research assistant runs.
"""

import mlflow


def log_research_run(
    question: str,
    answer: str,
    model: str = "llama3.2:3b",
) -> None:
    """
    Log a research assistant execution in MLflow.

    Args:
        question: Research question entered by the user.
        answer: Answer generated by the local LLM.
        model: Ollama model name.
    """
    mlflow.set_experiment("local-ai-research-assistant")

    with mlflow.start_run():
        # Store experiment parameters.
        mlflow.log_param("model", model)
        mlflow.log_param(
            "question_length",
            len(question),
        )

        # Store an output metric.
        mlflow.log_metric(
            "answer_length",
            len(answer),
        )